---
- name: Install prerequisites
  apk:
    name: "{{ bootstrap_prerequisite }}"
    state: present
    update_cache: true

- name: Install prerequisites
  apk:
    name: "{{ bootstrap_prerequisite }}"
    state: present
