---
- name: Install prerequisites
  yum:
    name: "{{ bootstrap_prerequisite }}"
    state: present
    update_cache: true
  register: task1

- name: Install packages for Centos 6 to be able to validate SNI
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - python-urllib3
    - pyOpenSSL
    - python-ndg_httpsclient
    - python-pyasn1
  when: ansible_distribution_major_version == '6'
  register: task2

- set_fact:
    state:
      changed: "{{ (task1.changed or task1.changed) }}"
