---
- name: Install prerequisites
  yum:
    name: "{{ bootstrap_prerequisite }}"
    state: present
    update_cache: true

- name: Install packages for Centos 6 to be able to validate SNI
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - python-urllib3
    - pyOpenSSL
    - python-ndg_httpsclient
    - python-pyasn1
  when: ansible_distribution_major_version == '6'
