---
- name: Include Distribution version specific variables
  include_vars: "{{ ansible_os_family }}-family.yml"
  when: ansible_os_family == 'Debian'

- include_tasks: "{{ ansible_distribution }}.yml"

- name: include cleanup
  include_role:
    name: cleanup
  when: state.changed
